### ISSUE TITLE
Problema con URIs de datos.gob.es

### ISSUE THREAD

**Issue by jperez4** [opencitydata/sector-publico-organismos#1]
Las siguientes URIs no están disponibles:

`http://datos.gob.es/def/sector-publico/organizacion#` 
`http://datos.gob.es/def/sector-publico/organizacion`
`http://datos.gob.es/def/sector-publico/organizacion.html`
`http://datos.gob.es/def/sector-publico/organizacion.rdf`
> Página no encontrada. No se ha encontrado el recurso solicitado

**Comment by ocorcho** [comment]
Actualizada URI completa en commit 699e03d1367676f8f5a53fff60c1fd2354cf3576
