### ISSUE TITLE
SKOS a ".../organizacion/..." en lugar de ".../organismo/..."

### ISSUE THREAD

**Issue by eminguela** [opencitydata/sector-publico-organismos#10]
En el comentario de la actualización de [25/07/2018] se indica que los SKOS apuntan a ".../organizacion/..." (y efectivamente funcionan):
Actualización de skos:ConceptScheme utilizados. Se han actualizado los de tipo de entidad (http://vocab.linkeddata.es/datosabiertos/kos/sector-publico/organizacion/tipo-entidad), nivel de administración (http://vocab.linkeddata.es/datosabiertos/kos/sector-publico/organizacion/nivel-administracion) y estado de la entidad (http://vocab.linkeddata.es/datosabiertos/kos/sector-publico/organizacion/estado-entidad).

Sin embargo, al menos en el html de la ontología, estos SKOS apuntan a ".../organismo/...", que fallan:
Ej: http://vocab.linkeddata.es/datosabiertos/kos/sector-publico/organismo/estado-entidad

**Comment by ocorcho** [comment]
Modificado el código de la ontología para incluir esta documentación, que aparecerá publicada en la versión HTML cuando se vuelva a publicar.
